### PR TITLE
Relax Codable Router type requirements

### LINKED ISSUE #1235: CodableClosure should use Decodable -> Encodable
## Context and Description
At the moment the CodableClosure forces the users that the request-object and the response-object is Codable. So if the response is only Encodable, it is not possible to use the Codable-Route.

### Environment Details
MacOS 10.13.3 (17D102)

Apple Swift version 4.0.3 (swiftlang-900.0.74.1 clang-900.0.39.2)
XCode Version 9.2 (9C40b)
Kitora Version 2.2.0

### Steps to Reproduce
1) 1. create a codable-route, for example
```
router.post("/users", handler: { (request: MyRequest, respondWith: (MyResponse?, RequestError?) -> Void) in
    respondWith(nil, nil)
})
```
2) MyRequest implements Decodable, MyResponse implements Encodable
3) Doesn't compile
4) Adding Codable to MyRequest and MyResponse will work

### PR DESCRIPTION
**Pull request by djones6**
## Description
Implementation of Kitura Evolution proposal: [Relax Type Constraints for Codable Routing](https://github.com/IBM-Swift/evolution/pull/11)

Resolves IBM-Swift/Kitura#1235 by relaxing the type requirements on the Codable Router to Decodable for input types, and Encodable for output types.

This enables a corresponding Pull Request in Kitura: IBM-Swift/Kitura#1242

As this is merely a relaxing of type constraints, it can be delivered in a patch.

## Motivation and Context

See IBM-Swift/Kitura#1235.

The Codable Router was designed with a symmetry in mind for types to be shared between the client and server side (KituraKit <-> Kitura), which requires those types to be both Encodable and Decodable.

In addition, for types that contain purely Codable attributes, conformance to Codable can be synthesized by the compiler.  However, there are cases where conformance must be implemented manually.

For cases where the user only wants to use type safety in a single direction (such as Decodable for a type that will only be received), we currently require them to implement conformance to Encodable (at least dummy conformance to satisfy the type requirement).

## How Has This Been Tested?

Tests have been added to Kitura in IBM-Swift/Kitura#1242 that are dependent on these changes, and those tests are passing.

## Checklist:

- [ ] If applicable, I have updated the documentation accordingly.
- [ ] If applicable, I have added tests to cover my changes.

### CODE REVIEW

**Review by ianpartridge — APPROVED** [review]
LGTM.

**Comment by djones6** [comment]
This is not quite ready.  Although this is now correctly typed, there is currently no way for a user to `POST` a `Decodable` type, because the Codable Router currently requires that an `Encodable` type be returned in the response.

We need to have a think about how the API should permit this, which may require an additional closure type to be defined - such as allowing just an `Id` to be returned with no body, or allowing a `(nil, nil)` or `(Identifier, nil, nil)` response.

**Comment by djones6** [comment]
https://github.com/IBM-Swift/Kitura/pull/1242/commits/d8ebc698f685540aa3002be6bfdd76d21c32f47d relaxes the requirements for the Codable router result handler to permit a `(nil, nil)` response.

If this is deemed acceptable, then this PR is ready to go.

**Comment by djones6** [comment]
https://github.com/IBM-Swift/evolution/pull/11 has been reviewed and approved.

**Pull request merged**
