### PR TITLE
Adding missing Bool type to QueryDecoder

### PR DESCRIPTION
**Pull request by hactar**
QueryDecoder cannot decode bools (QueryEncoder already includes bool encode support). I've added the missing switch case and a test. Tests pass on my machine.

### CODE REVIEW

**Review by sandmman — APPROVED** [review]
LGTM!

**Comment by ianpartridge** [comment]
Thanks @sandmman! This is a bugfix so SemVer patch is ok yeah?

**Comment by sandmman** [comment]
Yeah, that should be fine

**Comment by ianpartridge** [comment]
Thanks @hactar!

**Comment by ianpartridge** [comment]
Tagged as https://github.com/IBM-Swift/KituraContracts/releases/tag/0.0.21

**Pull request merged**
