### PR TITLE
Update TravisCI: Remove Swift 4.x; Add Swift 5.4

### PR DESCRIPTION
**Pull request by dannys42**

### CODE REVIEW

**Comment by dannys42** [comment]
@mbarnach @adam-rocska What are your thoughts on the changes here?  Apparently there's a minor change in JSONEncoder between Swift 4.x and Swift 5.x and JSON fragments are now supported.  But I think KituraContracts was relying on fragments not being supported.  It's a little inefficient, but I just threw in an extra check as I saw no option for JSONEncoder to disable allowing fragments.

**Comment by mbarnach** [comment]
🤔  Interesting... Are you sure this is problematic? Or more specifically, in which way was it problematic for you?

**Comment by dannys42** [comment]
I'm not entirely sure it's a problem... just that there was a unit test explicitly testing that error responses must not be JSON fragments.  So in the absence of more insight, I'm attempting to preserve that behavior.  Unfortunately the error that is thrown is not preserved, but I'm hoping that won't be an issue for any practical uses of the framework.

**Comment by mbarnach** [comment]
I think that's the expected behaviour. I cannot find a quick and easy way to do it without that extra test, but I'm wondering if we shouldn't put it under Debug or any other flag, as it is quite "intense" otherwise?

**Comment by dannys42** [comment]
@mbarnach yah, that sounds reasonable.

**Review by mbarnach — APPROVED** [review]
All good to me!

**Pull request merged**
