### PR TITLE
Address Unit Test warning about an unused variable

### PR DESCRIPTION
**Pull request by LowAmmo**
Also added the project file to the repo to make any future changes/modifications easier to do

Totally fine removing the project file, just thought it would make it easier for others to make changes in the future

### CODE REVIEW

**Comment by dannys42** [comment]
Thanks for updating the unit test.  Is there something the xcproject file gives you that the Package.swift file does not?  You should be able to open the folder from Xcode without the xcproject file and be able to run unit tests without issue.

**Comment by LowAmmo** [comment]
I'm still a newbie when it comes to SPM... I didn't know there was an easy to open a folder with a Package.swift in xcode, without a project file.

I'll have to give that a try on Monday, and see if it gives me any trouble... (I just assumed you had a lot of special config/settings in a local project file you didn't want to commit to master 😉 )

On a related note...thanks for the all the quick responses! Looking forward to just getting some of these repos updated to address these new compiler warnings - just to help clean up my (and anyone else's) app build! 😄

**Comment by LowAmmo** [comment]
@dannys42  - Yup, able to open from `Package.swift`, successfullly.

The few "issues" with this approach:
* Not seeing a way to target running tests on an iOS device (within Xcode)
  * So any iOS specific functionality can't be easily tested
  * Looks like there is a command-line way...I'm just more of a GUI person
* No code coverage easily generated (just hard to verify unit tests cover enough/everything)

But, I'm seeing that this is probably the "preferred" way to do a Swift package.  So, If you'd like, I can revert all my changes to add the Project file in (probably a pretty moot point on this repo, since there doesn't seem to be any iOS-specific logic, anyway).

Especially as I'm just a "visitor" on this repo...I'll gladly defer to however you prefer to manage things.

-Thanks!

**Comment by LowAmmo** [comment]
@dannys42 - got things cleaned up so just the necessary code changes are on the PR

**Comment by LowAmmo** [comment]
@dannys42 - Once you start begging...it's hard to stop, isn't it?!?! 😉  This is another one that would be great to have merged and released... 😄

**Review by dannys42 — APPROVED** [review]

**Pull request merged**
